doc-warnings: yes
test-warnings: yes
strictness: veryhigh
max-line-length: 80
pep257:
    disable: [D203, D401]
pep8:
    full: true
mccabe:
    options: {max-complexity: 15}
pylint:
    enable: [bad-continuation, fixme]
    options: {max-nested-blocks: 3}
python-targets:
    - 2
    - 3
