# Auto-generated by 'setup.py build', do not change !
tikz_shapes='''
%% Start of shape library. This part remains the same for all graph exports.
\\pgfdeclareshape{start}{
    \\anchor{center}{\pgfpoint{18}{18}}
    \\anchor{north}{\pgfpoint{18}{36}}
    \\anchor{south}{\pgfpoint{18}{0}}
    \\anchor{west}{\pgfpoint{0}{18}}
    \\anchor{east}{\pgfpoint{36}{18}}
    \\foregroundpath{
        \\pgfsetlinewidth{1.4}
        \\pgftransformshift{\pgfpoint{36}{36}}
        \\pgftransformrotate{180} 
        \\pgfsetfillcolor{white}
        \\pgfcircle{\pgfpoint{17.500000}{17.500000}}{9.000000}
\\pgfusepath{stroke, fill}
        \\pgfusepath{stroke}
}}
\\pgfdeclareshape{block}{
    \\anchor{center}{\pgfpoint{18}{18}}
    \\anchor{north}{\pgfpoint{18}{36}}
    \\anchor{south}{\pgfpoint{18}{0}}
    \\anchor{west}{\pgfpoint{0}{18}}
    \\anchor{east}{\pgfpoint{36}{18}}
    \\foregroundpath{
        \\pgfsetlinewidth{1.4}
        \\pgftransformshift{\pgfpoint{36}{36}}
        \\pgftransformrotate{180} 
        \\pgfsetfillcolor{white}
        \\pgfrect{\pgfpoint{0.700000}{0.700000}}{\pgfpoint{33.600000}{33.600000}}
\\pgfusepath{stroke, fill}
        \\pgfusepath{stroke}
}}
\\pgfdeclareshape{out_of}{
    \\anchor{center}{\pgfpoint{18}{18}}
    \\anchor{north}{\pgfpoint{18}{36}}
    \\anchor{south}{\pgfpoint{18}{0}}
    \\anchor{west}{\pgfpoint{0}{18}}
    \\anchor{east}{\pgfpoint{36}{18}}
    \\foregroundpath{
        \\pgfsetlinewidth{1.4}
        \\pgftransformshift{\pgfpoint{36}{36}}
        \\pgftransformrotate{180} 
        \\pgfsetfillcolor{white}
        \\pgfcircle{\pgfpoint{17.500000}{17.500000}}{16.800000}
\\pgfusepath{stroke, fill}
        \\pgfusepath{stroke}
}}
\\pgfdeclareshape{end}{
    \\anchor{center}{\pgfpoint{18}{18}}
    \\anchor{north}{\pgfpoint{18}{36}}
    \\anchor{south}{\pgfpoint{18}{0}}
    \\anchor{west}{\pgfpoint{0}{18}}
    \\anchor{east}{\pgfpoint{36}{18}}
    \\foregroundpath{
        \\pgfsetlinewidth{1.4}
        \\pgftransformshift{\pgfpoint{36}{36}}
        \\pgftransformrotate{180} 
        \\pgfsetfillcolor{white}
        \\pgfcircle{\pgfpoint{17.500000}{17.500000}}{9.000000}
\\pgfusepath{stroke, fill}
        \\pgfusepath{stroke}
}}
\\pgfdeclareshape{houseEvent}{
    \\anchor{center}{\pgfpoint{18}{18}}
    \\anchor{north}{\pgfpoint{18}{36}}
    \\anchor{south}{\pgfpoint{18}{0}}
    \\anchor{west}{\pgfpoint{0}{18}}
    \\anchor{east}{\pgfpoint{36}{18}}
    \\foregroundpath{
        \\pgfsetlinewidth{1.4}
        \\pgftransformshift{\pgfpoint{36}{36}}
        \\pgftransformrotate{180} 
        \\pgfsetfillcolor{white}
        \\pgfpathsvg{M 17.5,0.7 L 34.3,15 34.3,34.3 0.7,34.3 0.7,15 z}
        \\pgfusepath{stroke}
}}
\\pgfdeclareshape{fdepGate}{
    \\anchor{center}{\pgfpoint{18}{18}}
    \\anchor{north}{\pgfpoint{18}{36}}
    \\anchor{south}{\pgfpoint{18}{0}}
    \\anchor{west}{\pgfpoint{0}{18}}
    \\anchor{east}{\pgfpoint{36}{18}}
    \\foregroundpath{
        \\pgfsetlinewidth{1.4}
        \\pgftransformshift{\pgfpoint{36}{36}}
        \\pgftransformrotate{180} 
        \\pgfsetfillcolor{white}
        \\pgfpathsvg{M 0.7,17.5 34.3,17.5}
        \\pgfpathsvg{M 1,34.3 17.5,19 34,34.3}
        \\pgfrect{\pgfpoint{0.700000}{0.700000}}{\pgfpoint{33.600000}{33.600000}}
\\pgfusepath{stroke, fill}
        \\pgfusepath{stroke}
}}
\\pgfdeclareshape{priorityAndGate}{
    \\anchor{center}{\pgfpoint{18}{18}}
    \\anchor{north}{\pgfpoint{18}{36}}
    \\anchor{south}{\pgfpoint{18}{0}}
    \\anchor{west}{\pgfpoint{0}{18}}
    \\anchor{east}{\pgfpoint{36}{18}}
    \\foregroundpath{
        \\pgfsetlinewidth{1.4}
        \\pgftransformshift{\pgfpoint{36}{36}}
        \\pgftransformrotate{180} 
        \\pgfsetfillcolor{white}
        \\pgfpathsvg{M 0.7,34.3 L 34.3,34.3 34.3,21 C 34.3,21 34.3,0.7 17.5,0.7 C 0.7,0.7 0.7,21 0.7,21 z}
        \\pgfpathsvg{M 1,34.3 17.5,2.8 34,34.3}
        \\pgfusepath{stroke}
}}
\\pgfdeclareshape{orGate}{
    \\anchor{center}{\pgfpoint{18}{18}}
    \\anchor{north}{\pgfpoint{18}{36}}
    \\anchor{south}{\pgfpoint{18}{0}}
    \\anchor{west}{\pgfpoint{0}{18}}
    \\anchor{east}{\pgfpoint{36}{18}}
    \\foregroundpath{
        \\pgfsetlinewidth{1.4}
        \\pgftransformshift{\pgfpoint{36}{36}}
        \\pgftransformrotate{180} 
        \\pgfsetfillcolor{white}
        \\pgfpathsvg{M 0.7,34.3 C 12.6,28 22.4,28 34.3,34.3 C 34.3,21 28,7 17.5,0.7 C 7,7 0.7,21 0.7,34.3 z}
        \\pgfusepath{stroke}
}}
\\pgfdeclareshape{inhibitGate}{
    \\anchor{center}{\pgfpoint{18}{18}}
    \\anchor{north}{\pgfpoint{18}{36}}
    \\anchor{south}{\pgfpoint{18}{0}}
    \\anchor{west}{\pgfpoint{0}{18}}
    \\anchor{east}{\pgfpoint{36}{18}}
    \\foregroundpath{
        \\pgfsetlinewidth{1.4}
        \\pgftransformshift{\pgfpoint{36}{36}}
        \\pgftransformrotate{180} 
        \\pgfsetfillcolor{white}
        \\pgfpathsvg{M 17.5,0.7 L 34.3,11 34.3,24 17.5,34.3 0.7,24 0.7,11 z}
        \\pgfusepath{stroke}
}}
\\pgfdeclareshape{votingOrGate}{
    \\anchor{center}{\pgfpoint{17}{17}}
    \\anchor{north}{\pgfpoint{17}{35}}
    \\anchor{south}{\pgfpoint{17}{0}}
    \\anchor{west}{\pgfpoint{0}{17}}
    \\anchor{east}{\pgfpoint{35}{17}}
    \\foregroundpath{
        \\pgfsetlinewidth{1.4}
        \\pgftransformshift{\pgfpoint{35}{35}}
        \\pgftransformrotate{180} 
        \\pgfsetfillcolor{white}
        \\pgfpathsvg{M 0.7,34.3 C 12.6,28 22.4,28 34.3,34.3 C 34.3,21 28,7 17.5,0.7 C 7,7 0.7,21 0.7,34.3 z}
        \\pgfpathsvg{M 8.4,9.1 17.5,28.0 26.6,9.1}
        \\pgfusepath{stroke}
}}
\\pgfdeclareshape{seqGate}{
    \\anchor{center}{\pgfpoint{18}{18}}
    \\anchor{north}{\pgfpoint{18}{36}}
    \\anchor{south}{\pgfpoint{18}{0}}
    \\anchor{west}{\pgfpoint{0}{18}}
    \\anchor{east}{\pgfpoint{36}{18}}
    \\foregroundpath{
        \\pgfsetlinewidth{1.4}
        \\pgftransformshift{\pgfpoint{36}{36}}
        \\pgftransformrotate{180} 
        \\pgfsetfillcolor{white}
        \\pgfpathsvg{M 0.7,17.5 34.3,17.5}
        \\pgfrect{\pgfpoint{0.700000}{0.700000}}{\pgfpoint{33.600000}{33.600000}}
\\pgfusepath{stroke, fill}
        \\pgfusepath{stroke}
}}
\\pgfdeclareshape{topEvent}{
    \\anchor{center}{\pgfpoint{18}{18}}
    \\anchor{north}{\pgfpoint{18}{36}}
    \\anchor{south}{\pgfpoint{18}{0}}
    \\anchor{west}{\pgfpoint{0}{18}}
    \\anchor{east}{\pgfpoint{36}{18}}
    \\foregroundpath{
        \\pgfsetlinewidth{1.4}
        \\pgftransformshift{\pgfpoint{36}{36}}
        \\pgftransformrotate{180} 
        \\pgfsetfillcolor{white}
        \\pgfrect{\pgfpoint{0.700000}{0.700000}}{\pgfpoint{33.600000}{33.600000}}
\\pgfusepath{stroke, fill}
        \\pgfusepath{stroke}
}}
\\pgfdeclareshape{basicEventSet}{
    \\anchor{center}{\pgfpoint{18}{18}}
    \\anchor{north}{\pgfpoint{18}{36}}
    \\anchor{south}{\pgfpoint{18}{0}}
    \\anchor{west}{\pgfpoint{0}{18}}
    \\anchor{east}{\pgfpoint{36}{18}}
    \\foregroundpath{
        \\pgfsetlinewidth{1.4}
        \\pgftransformshift{\pgfpoint{36}{36}}
        \\pgftransformrotate{180} 
        \\pgfsetfillcolor{white}
        \\pgfcircle{\pgfpoint{20.000000}{20.000000}}{14.300000}
\\pgfusepath{stroke, fill}
        \\pgfcircle{\pgfpoint{17.500000}{17.500000}}{14.300000}
\\pgfusepath{stroke, fill}
        \\pgfcircle{\pgfpoint{15.000000}{15.000000}}{14.300000}
\\pgfusepath{stroke, fill}
        \\pgfusepath{stroke}
}}
\\pgfdeclareshape{cspGate}{
    \\anchor{center}{\pgfpoint{18}{18}}
    \\anchor{north}{\pgfpoint{18}{36}}
    \\anchor{south}{\pgfpoint{18}{0}}
    \\anchor{west}{\pgfpoint{0}{18}}
    \\anchor{east}{\pgfpoint{36}{18}}
    \\foregroundpath{
        \\pgfsetlinewidth{1.4}
        \\pgftransformshift{\pgfpoint{36}{36}}
        \\pgftransformrotate{180} 
        \\pgfsetfillcolor{white}
        \\pgfpathsvg{M 0.7,17.5 34.3,17.5}
        \\pgfpathsvg{M 17.5,34.3 17.5,25.55 34.3,25.55}
        \\pgfrect{\pgfpoint{0.700000}{0.700000}}{\pgfpoint{33.600000}{33.600000}}
\\pgfusepath{stroke, fill}
        \\pgfusepath{stroke}
}}
\\pgfdeclareshape{endNode}{
    \\anchor{center}{\pgfpoint{18}{18}}
    \\anchor{north}{\pgfpoint{18}{36}}
    \\anchor{south}{\pgfpoint{18}{0}}
    \\anchor{west}{\pgfpoint{0}{18}}
    \\anchor{east}{\pgfpoint{36}{18}}
    \\foregroundpath{
        \\pgfsetlinewidth{1.4}
        \\pgftransformshift{\pgfpoint{36}{36}}
        \\pgftransformrotate{180} 
        \\pgfsetfillcolor{white}
        \\pgfcircle{\pgfpoint{17.500000}{17.500000}}{16.800000}
\\pgfusepath{stroke, fill}
        \\pgfusepath{stroke}
}}
\\pgfdeclareshape{andGate}{
    \\anchor{center}{\pgfpoint{18}{18}}
    \\anchor{north}{\pgfpoint{18}{36}}
    \\anchor{south}{\pgfpoint{18}{0}}
    \\anchor{west}{\pgfpoint{0}{18}}
    \\anchor{east}{\pgfpoint{36}{18}}
    \\foregroundpath{
        \\pgfsetlinewidth{1.4}
        \\pgftransformshift{\pgfpoint{36}{36}}
        \\pgftransformrotate{180} 
        \\pgfsetfillcolor{white}
        \\pgfpathsvg{M 0.7,34.3 L 34.3,34.3 34.3,21 C 34.3,21 34.3,0.7 17.5,0.7 C 0.7,0.7 0.7,21 0.7,21 z}
        \\pgfusepath{stroke}
}}
\\pgfdeclareshape{intermediateEvent}{
    \\anchor{center}{\pgfpoint{18}{18}}
    \\anchor{north}{\pgfpoint{18}{36}}
    \\anchor{south}{\pgfpoint{18}{0}}
    \\anchor{west}{\pgfpoint{0}{18}}
    \\anchor{east}{\pgfpoint{36}{18}}
    \\foregroundpath{
        \\pgfsetlinewidth{1.4}
        \\pgftransformshift{\pgfpoint{36}{36}}
        \\pgftransformrotate{180} 
        \\pgfsetfillcolor{white}
        \\pgfrect{\pgfpoint{0.700000}{0.700000}}{\pgfpoint{33.600000}{33.600000}}
\\pgfusepath{stroke, fill}
        \\pgfusepath{stroke}
}}
\\pgfdeclareshape{transferIn}{
    \\anchor{center}{\pgfpoint{18}{18}}
    \\anchor{north}{\pgfpoint{18}{36}}
    \\anchor{south}{\pgfpoint{18}{0}}
    \\anchor{west}{\pgfpoint{0}{18}}
    \\anchor{east}{\pgfpoint{36}{18}}
    \\foregroundpath{
        \\pgfsetlinewidth{1.4}
        \\pgftransformshift{\pgfpoint{36}{36}}
        \\pgftransformrotate{180} 
        \\pgfsetfillcolor{white}
        \\pgfpathsvg{M 17.5,1 35,34.3 1,34.3 z}
        \\pgfusepath{stroke}
}}
\\pgfdeclareshape{intermediateEventSet}{
    \\anchor{center}{\pgfpoint{18}{18}}
    \\anchor{north}{\pgfpoint{18}{36}}
    \\anchor{south}{\pgfpoint{18}{0}}
    \\anchor{west}{\pgfpoint{0}{18}}
    \\anchor{east}{\pgfpoint{36}{18}}
    \\foregroundpath{
        \\pgfsetlinewidth{1.4}
        \\pgftransformshift{\pgfpoint{36}{36}}
        \\pgftransformrotate{180} 
        \\pgfsetfillcolor{white}
        \\pgfrect{\pgfpoint{7.700000}{7.700000}}{\pgfpoint{26.600000}{26.600000}}
\\pgfusepath{stroke, fill}
        \\pgfrect{\pgfpoint{4.200000}{4.200000}}{\pgfpoint{26.600000}{26.600000}}
\\pgfusepath{stroke, fill}
        \\pgfrect{\pgfpoint{0.700000}{0.700000}}{\pgfpoint{26.600000}{26.600000}}
\\pgfusepath{stroke, fill}
        \\pgfusepath{stroke}
}}
\\pgfdeclareshape{xorGate}{
    \\anchor{center}{\pgfpoint{17}{17}}
    \\anchor{north}{\pgfpoint{17}{35}}
    \\anchor{south}{\pgfpoint{17}{0}}
    \\anchor{west}{\pgfpoint{0}{17}}
    \\anchor{east}{\pgfpoint{35}{17}}
    \\foregroundpath{
        \\pgfsetlinewidth{1.4}
        \\pgftransformshift{\pgfpoint{35}{35}}
        \\pgftransformrotate{180} 
        \\pgfsetfillcolor{white}
        \\pgfpathsvg{M 0.7,34.3 C 12.6,28 22.4,28 34.3,34.3 C 34.3,21 28,7 17.5,0.7 C 7,7 0.7,21 0.7,34.3 z}
        \\pgfpathsvg{M 0.7,34.3 L 17.5,1.4 34.3,34.3}
        \\pgfusepath{stroke}
}}
\\pgfdeclareshape{basicEvent}{
    \\anchor{center}{\pgfpoint{18}{18}}
    \\anchor{north}{\pgfpoint{18}{36}}
    \\anchor{south}{\pgfpoint{18}{0}}
    \\anchor{west}{\pgfpoint{0}{18}}
    \\anchor{east}{\pgfpoint{36}{18}}
    \\foregroundpath{
        \\pgfsetlinewidth{1.4}
        \\pgftransformshift{\pgfpoint{36}{36}}
        \\pgftransformrotate{180} 
        \\pgfsetfillcolor{white}
        \\pgfcircle{\pgfpoint{17.500000}{17.500000}}{16.800000}
\\pgfusepath{stroke, fill}
        \\pgfusepath{stroke}
}}
\\pgfdeclareshape{undevelopedEvent}{
    \\anchor{center}{\pgfpoint{18}{18}}
    \\anchor{north}{\pgfpoint{18}{36}}
    \\anchor{south}{\pgfpoint{18}{0}}
    \\anchor{west}{\pgfpoint{0}{18}}
    \\anchor{east}{\pgfpoint{36}{18}}
    \\foregroundpath{
        \\pgfsetlinewidth{1.4}
        \\pgftransformshift{\pgfpoint{36}{36}}
        \\pgftransformrotate{180} 
        \\pgfsetfillcolor{white}
        \\pgfpathsvg{M 17.5,0.7 34.3,17.5 17.5,34.3 0.7,17.5 z}
        \\pgfusepath{stroke}
}}
\\pgfdeclareshape{redundancyVariation}{
    \\anchor{center}{\pgfpoint{18}{18}}
    \\anchor{north}{\pgfpoint{18}{36}}
    \\anchor{south}{\pgfpoint{18}{0}}
    \\anchor{west}{\pgfpoint{0}{18}}
    \\anchor{east}{\pgfpoint{36}{18}}
    \\foregroundpath{
        \\pgfsetlinewidth{1.4}
        \\pgftransformshift{\pgfpoint{36}{36}}
        \\pgftransformrotate{180} 
        \\pgfsetfillcolor{white}
        \\pgfsetdash{{4.2}{1.4}}{0}
        \\pgfpathsvg{M 0.7,24.5 C 0.7,38 34.3,38 34.3,24.5 L 28,21 C 26.6,10.5 22.4,3.5 17.5,0.7 C 12.6,3.5 8.4,10.5 7,21 z}
        \\pgfusepath{stroke}
}}
\\pgfdeclareshape{featureVariation}{
    \\anchor{center}{\pgfpoint{18}{18}}
    \\anchor{north}{\pgfpoint{18}{36}}
    \\anchor{south}{\pgfpoint{18}{0}}
    \\anchor{west}{\pgfpoint{0}{18}}
    \\anchor{east}{\pgfpoint{36}{18}}
    \\foregroundpath{
        \\pgfsetlinewidth{1.4}
        \\pgftransformshift{\pgfpoint{36}{36}}
        \\pgftransformrotate{180} 
        \\pgfsetfillcolor{white}
        \\pgfsetdash{{4.2}{1.4}}{0}
        \\pgfpathsvg{M 0.7,24 C 0.7,24 3.5,34 17.5,34.3 31.5,34.3 34.3,24 34.3,24 L 21,0.7 14,0.7 z}
        \\pgfusepath{stroke}
}}
%% End of shape library. This part below is unique for all graph exports.
'''