text = {
	90	: "Graph error - The decomposition number must by greater than zero.",
	100	: "Graph error - There is no TOP event.",
	110	: "Event error - A TOP event can only have one child.",
	115	: "Event error - A TOP event cannot have an event set as child.",
	120 : "Gate error - This gate must have at least one child.",
	130 : "Graph error - Your graph contains an undeveloped event, so it cannot be analyzed completely.",
	140	: "Gate error - Your value for k must be greater than zero.",
	150	: "Gate error - Your value for k cannot be greater than the number of children for the gate.",
	160 : "Event error - Basic events cannot have children.",
	170 : "Event error - All basic events must have some probability value for the analysis.",
	180	: "Event error - The probability value must be between zero and one.",
	190	: "Event error - This fuzzy probability is invalid.",
	200 : "Event error - An intermediate event can only have one child.",
	210	: "Event error - An intermediate event can only have one child.",
	220 : "Event error - The event set cannot be optional with this parent.",
	230	: "Event error - The quantity property value must be greater than zero.",
	240	: "Event error - An event set is not allowed with this parent.",
	250 : "Variation point error - At least one child is needed.",
	260	: "Variation point error - Exactly one child is needed.",
	270	: "Variation point error - Only event sets are allowed as children.",
	280	: "Variation point error - A positive range is needed.",
	290	: "Variation point error - The N-formula is missing.",
	300 : "Variation point error - The N-formula is invalid.",
	310 : "TransferIn error - No children are allowed.",
	320 : "TransferIn error - Only one annotation is allowed.",
	330 : "TransferIn error - The analysis result of the linked graph is missing or invalid.",
	340 : "TransferIn error - Both graphs must have the same decomposition number.",
	350 : "TransferIn error - The linked graph has no configuration that is cheaper than the given limit.",
	500	: "Gate warning - Gates are expected to have more than one child.",
	510	: "Gate warning - Gates should not have a variation point as parent.",
	520	: "Event warning - Variation point children should not be optional.",
	530	: "Variation point warning - You should provide a name here.",
	540	: "Event warning - Optional events should have a cost property.",
	550	: "Event warning - The specified quantity value will be ignored, because of the parent.",
	560 : "Variation point warning - More than one child is expected here."
}