#!/bin/bash
#
# fuzzTreeAnalysis 
#
# Make sure that you link this script in /etc/init.d and enable it's startup:
# chkconfig --level 345 fuzzTreeAnalysis on
#
### BEGIN INIT INFO
# Provides: fuzzTreeAnalysis 
# Required-Start: $local_fs $remote_fs $network
# Required-Stop: $local_fs $remote_fs $network
# chkconfig: 345 99 01
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

prog="FuzzTrees Analysis Server"
exec=/home/fuzztrees/fuzzed/analysis/jar/fuzzTreeAnalysis.sh
pidfile=/var/run/fuzzTreeAnalysis.pid
lockfile=/var/lock/subsys/fuzzTreeAnalysis

start() {
    echo -n $"Starting $prog ..."
    daemon --pidfile=${pidfile} $exec 
    retval=$?
    echo
    if [ $retval -eq 0 ]; then
        touch $lockfile || retval=4
    fi
    return $retval
}

stop() {
    echo -n $"Stopping $prog ..."
    killproc -p ${pidfile} $exec
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}

reload() {
    restart
}

force_reload() {
    restart
}

rh_status() {
    # run checks to determine if the service is running or use generic status
    status -p ${pidfile} -l ${lockfile} $exec
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}

case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
        exit 2
esac
exit $?
