#! /bin/sh

### BEGIN INIT INFO
# Provides:          fuzzed-analysis 
# Required-Start:    $local_fs $remote_fs
# Required-Stop:
# X-Start-Before:    
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Java Tomcat server for FuzzEd analysis backend
### END INIT INFO

THIS=/etc/init.d/fuzzed-analysis
SCRIPTDIR=/root/fuzztrees/

set -e

case "$1" in
  start)
        start-stop-daemon --start --background --name fuzzed-analysis --exec /usr/bin/java --chdir $SCRIPTDIR --  -Djava.util.logging.config.file=analysis/jar/logging.properties -jar analysis/jar/fuzzTreeAnalysis.jar -runServer
        ;;
  stop)
        start-stop-daemon --stop --name fuzzed-analysis
        ;;
  *)
        echo "Usage: $THIS {start|stop}" >&2
        exit 1
        ;;
esac

exit 0

