# Dockerfile for ORE backend

FROM ubuntu:xenial

RUN apt-get update \
    && apt-get install -y texlive \
    && rm -rf /var/lib/apt/lists/* 

RUN apt-get update \
    && apt-get install -y python python-pip libboost libboost-graph libboost-date-time libboost-system libboost-filesystem libboost-program-options libxerces-c xsdcxx \
    && rm -rf /var/lib/apt/lists/* 

RUN pip install requests

COPY backends/docker/startup.sh /startup.sh

EXPOSE 8000
CMD ["bash", "/startup.sh"]
